#!/usr/bin/env sh
#copy this file to spectral/.git/hooks/pre-commit

set -eu

echo "Checking formatting..."
unformatted="$(gofmt -l .)"
if [ -n "$unformatted" ]; then
  echo "The following files are unformatted with gofmt:"
  echo "$unformatted"
  exit 1
fi

echo "Running go vet..."
go vet ./...

echo "Running Go tests..."
go test ./...
